// library.add(
//   faAngleDoubleLeft,
//   faAngleDoubleRight,
//   faCog,
//   faExclamationTriangle,
//   faEye,
//   faEyeSlash,
//   faFile,
//   faHeart,
//   faInfoCircle,
//   faLock,
//   faMinus,
//   faPlus,
//   faSignInAlt,
//   faSignOutAlt,
//   faUser,
//   faGithub,
//   faEtsy,
//   faTwitter
// );
//