services:
  console-db:
    image: postgres
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=password1234
      - POSTGRES_DB=console
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "console", "-U", "postgres"]
      interval: 30s
      timeout: 5s
      retries: 5